### ISSUE TITLE
Model signature expects a dummy column

### ISSUE THREAD

**Issue by alex000kim** [iterative/mlem#371] opened 2022-08-03 16:06 UTC
When a model is saved with MLEM, the model expects the input to have a dummy value e.g.:
https://github.com/iterative/demo-bank-customer-churn/blob/main/.mlem/model/clf-model.mlem#L15
I suspect I comes from a dataframe's index when pandas dataframe is passed to the model during training.

**Comment by mike0sv** [comment] 2022-08-03 18:57
closing as a duplicate of https://github.com/iterative/mlem/issues/280

**Closed by mike0sv** 2022-08-03 18:57 UTC
