### ISSUE TITLE
Error saving custom sklearn transformer and pipeline

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem#623] opened 2023-02-28 09:03 UTC
reported by @ykasimov

```bash
pip install pandas xgboost scikit-learn mlem
```

```py
from sklearn.base import BaseEstimator, TransformerMixin
from xgboost import XGBClassifier
from mlem.api import save
import pandas as pd

from sklearn.pipeline import Pipeline
import typing


class SubtractTransform(BaseEstimator, TransformerMixin):
    def __init__(
        self
    ) -> None:
        super().__init__()

    def fit(
        self, X: pd.DataFrame, y: typing.Optional[pd.DataFrame] = None
    ) :
        print("fit")
        return self

    def transform(
        self,
        X: pd.DataFrame,
    ):
        print("transform")
        X_ = X.copy()  # creating a copy to avoid changes to original dataset
        return X_



clf = Pipeline(
        steps=[
            (
                "SubtractTransform",
                SubtractTransform(
                ),
            ),
            (
                "xgboost",
                XGBClassifier(
                ),
            ),
        ]
)

x = [[0,0],[0,1], [1,0], [1,1]]
y = [0, 1, 1, 0]
clf.fit(x, y)
save(clf, "model.clf", sample_data=x)
```

```py
$ python train.py
fit
transform
transform
transform
Traceback (most recent call last):
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/mlem/utils/module.py", line 456, in wrapper
    source = dill.source.getsource(obj)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/dill/source.py", line 374, in getsource
    lines, lnum = getsourcelines(object, enclosing=enclosing)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/dill/source.py", line 345, in getsourcelines
    code, n = getblocks(object, lstrip=lstrip, enclosing=enclosing, locate=True)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/dill/source.py", line 271, in getblocks
    lines, lnum = findsource(object)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/dill/source.py", line 215, in findsource
    line = lines[lnum]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/train.py", line 50, in <module>
    save(clf, "model.clf", sample_data=x)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/mlem/telemetry.py", line 50, in inner
    return f(*args, **kwargs)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/mlem/core/metadata.py", line 122, in save
    meta = get_object_metadata(
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/mlem/core/metadata.py", line 53, in get_object_metadata
    return MlemModel.from_obj(
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/mlem/core/objects.py", line 786, in from_obj
    mlem_model.add_processor(MAIN_PROCESSOR_NAME, mt)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/mlem/core/objects.py", line 810, in add_processor
    self.requirements += model_type.get_requirements().expanded
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/mlem/contrib/sklearn.py", line 86, in get_requirements
    super().get_requirements()
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/mlem/core/model.py", line 341, in get_requirements
    ) + get_object_requirements(self.model)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/mlem/utils/module.py", line 643, in get_object_requirements
    a.dump(obj)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/dill/_dill.py", line 394, in dump
    StockPickler.dump(self, obj)
  File "/Users/aguschin/.pyenv/versions/3.10.7/lib/python3.10/pickle.py", line 487, in dump
    self.save(obj)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/mlem/utils/module.py", line 614, in save
    return super().save(obj, save_persistent_id)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/Users/aguschin/.pyenv/versions/3.10.7/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/aguschin/.pyenv/versions/3.10.7/lib/python3.10/pickle.py", line 717, in save_reduce
    save(state)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/mlem/utils/module.py", line 614, in save
    return super().save(obj, save_persistent_id)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/Users/aguschin/.pyenv/versions/3.10.7/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/dill/_dill.py", line 1186, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/Users/aguschin/.pyenv/versions/3.10.7/lib/python3.10/pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/aguschin/.pyenv/versions/3.10.7/lib/python3.10/pickle.py", line 998, in _batch_setitems
    save(v)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/mlem/utils/module.py", line 614, in save
    return super().save(obj, save_persistent_id)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/Users/aguschin/.pyenv/versions/3.10.7/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/Users/aguschin/.pyenv/versions/3.10.7/lib/python3.10/pickle.py", line 932, in save_list
    self._batch_appends(obj)
  File "/Users/aguschin/.pyenv/versions/3.10.7/lib/python3.10/pickle.py", line 956, in _batch_appends
    save(x)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/mlem/utils/module.py", line 614, in save
    return super().save(obj, save_persistent_id)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/Users/aguschin/.pyenv/versions/3.10.7/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/Users/aguschin/.pyenv/versions/3.10.7/lib/python3.10/pickle.py", line 887, in save_tuple
    save(element)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/mlem/utils/module.py", line 614, in save
    return super().save(obj, save_persistent_id)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/Users/aguschin/.pyenv/versions/3.10.7/lib/python3.10/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/aguschin/.pyenv/versions/3.10.7/lib/python3.10/pickle.py", line 687, in save_reduce
    save(cls)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/mlem/utils/module.py", line 614, in save
    return super().save(obj, save_persistent_id)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/Users/aguschin/.pyenv/versions/3.10.7/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/mlem/utils/module.py", line 495, in save_type_with_classvars
    pickler.save(attr)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/mlem/utils/module.py", line 614, in save
    return super().save(obj, save_persistent_id)
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/Users/aguschin/.pyenv/versions/3.10.7/lib/python3.10/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/mlem/utils/module.py", line 474, in wrapper
    raise Exception(
Exception: Cannot parse code for <function SubtractTransform.transform at 0x136e312d0> from /Users/aguschin/Git/iterative/mlem-docker-bug/.venv/lib/python3.10/site-packages/sklearn/utils/_set_output.py
```

**Comment by aguschin** [comment] 2023-03-03 02:48
Another error with this model: if you try to `mlem.api.load` this, you get:

```py
AttributeError: Can't get attribute 'SubtractTransform' on <module 'main' from '/Users/yurykasimov/Documents/dvc_playground/custom_transformer/load.py'> 
```

the workaround to that is to import ``SubtractTransform`` explicitly. 

However it leads to another error:

```python
mlem.core.errors.HookNotFound: No suitable ModelHook for object of type "Pipeline". Registered hooks: [<class 'mlem.contrib.callable.CallableModelType'>]
```

the workaround for that is to add `import sklearn` to the script. 

Needs to be investigated why mlem fails to discover the hooks.

**Comment by mike0sv** [comment] 2023-03-09 20:47
I can't reproduce original issue, copy-pasted and it just worked. Maybe share your env and I will try to re-create it.

As for loading, you need to do two things, if you are using something custom with mlem.
1.  Always use `if __name__ == '__main__'` syntax. When python imports a module, it actually just runs in. Since we need the code to recreate the object you saved, it means that fit and save code will run every time you try to load it, unless you put into main.
2. Put everything custom in a separate module (not the one you are running). The running module in python is always called `__main__` instead of the actual name. Because of that when we save the model with custom stuff, `__main__` is treated as a requirement. When you load it, there is a collision with the `__main__` module that you run your code from. This can work in some cases, but there is no guarantee.

Those are limitations of python and pickle/dill and there is nothing we can do about it, except put it somewhere in docs

**Comment by aguschin** [comment] 2023-03-11 02:06
After that, do `pip install scikit-learn=1.1.1` and try to load the model:

```py
(.venv) tmp %f $ python load.py                                                                                                                  28.53s
Traceback (most recent call last):
  File "/Users/aguschin/Git/iterative/tmp/load.py", line 4, in <module>
    load("model.clf")
  File "/Users/aguschin/Git/iterative/tmp/.venv/lib/python3.9/site-packages/mlem/core/metadata.py", line 156, in load
    meta = load_meta(
  File "/Users/aguschin/Git/iterative/tmp/.venv/lib/python3.9/site-packages/mlem/telemetry.py", line 50, in inner
    return f(*args, **kwargs)
  File "/Users/aguschin/Git/iterative/tmp/.venv/lib/python3.9/site-packages/mlem/core/metadata.py", line 245, in load_meta
    meta.load_value()
  File "/Users/aguschin/Git/iterative/tmp/.venv/lib/python3.9/site-packages/mlem/core/objects.py", line 853, in load_value
    self.model_type.load(self.relative_artifacts)
  File "/Users/aguschin/Git/iterative/tmp/.venv/lib/python3.9/site-packages/mlem/core/model.py", line 277, in load
    self.model = self.io.load(artifacts)
  File "/Users/aguschin/Git/iterative/tmp/.venv/lib/python3.9/site-packages/mlem/core/model.py", line 98, in load
    return pickle.load(f)
AttributeError: Can't get attribute 'SubtractTransform' on <module '__main__' from '/Users/aguschin/Git/iterative/tmp/load.py'>
```

**Comment by mike0sv** [comment] 2023-03-13 22:08
I reproduced and investigated original error.
Loading error should be fixed too (but you still need `main` for it to work properly)

**Closed** 2023-03-14 08:20 UTC
Labels: bug, serialization, p1-high
